import React from 'react'
import './globals.css'
import TODOProvider from '@/components/Provider'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = () => {
    return <TODOProvider />
}

export default RootLayout;