import './globals.css'
import { Roboto } from 'next/font/google';
import appStore from '@/redux/store'
import { Provider } from 'react-redux'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Provider store={appStore}>
      <html lang="en">
        <body className={roboto.className}>
          {children}
        </body>
      </html>
    </Provider>
  )
}
